version: '2'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile_jupyter
    ports:
     - "8888:8888"
    volumes:
     - .:/home
     - /Users/caseyjlaw/code/alnotebook:/home/agdir
  elastic:
    build:
      context: .
      dockerfile: Dockerfile_elastic
    command: elasticsearch
    working_dir: /home
    ports:
     - "9200:9200"
     - "9300:9300"
  hub:
    build:
      context: .
      dockerfile: Dockerfile_jupyterhub
    working_dir: /home
    ports:
     - "8000:8000"